# Locks to stop the twist inputs.
# For each lock:
# - topic   : input topic that provides the lock; it must be of type std_msgs::Bool?!!! 
# - timeout : == 0.0 -> not used
#              > 0.0 -> the lock is supposed to published at a certain frequency in order
#                       to detect that the publisher is alive; the timeout in seconds allows
#                       to detect that, and if the publisher dies we will enable the lock
# - priority: priority in the range [0, 255], so all the topics with priority lower than it
#             will be stopped/disabled
locks:
-
  name    : chat1
  topic   : chat1_lock
  timeout : 0.0
  # Same priority as joystick control, so it'll not block it.
  priority: 11
-
  name    : chat2
  topic   : chat2_lock
  timeout : 0.0
  # Same priority as joystick control, so it'll not block it.
  priority: 40
-
  name    : chat3
  topic   : chat3_lock
  timeout : 0.0
  # Same priority as joystick control, so it'll not block it.
  priority: 60
